#!/usr/bin/env node

/**
 * CLI for generating TypeScript type definitions from JSON configuration files
 * This script reads JSON config files and creates precise TypeScript types
 */

import { createHash } from 'node:crypto'
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname } from 'node:path'

import {
	autoGenerateTypes,
	generateConfigTypes,
} from '../lib/types/generator.js'
import { cliLogger } from '../lib/utils/logger.js'

const parseArgs = (): { isAutoMode: boolean; paths: string[] } => {
	const args = process.argv.slice(2)
	return {
		isAutoMode: args.includes('--auto'),
		paths: args.filter(arg => !arg.startsWith('--')),
	}
}

const generateWithPaths = (configDir: string, outputFile: string): void => {
	const outputDir = dirname(outputFile)
	if (!existsSync(outputDir)) {
		mkdirSync(outputDir, { recursive: true })
	}

	// Check if regeneration is needed (same logic as in generator.ts)
	if (existsSync(outputFile)) {
		try {
			const newContent = generateConfigTypes(configDir)
			const newHash = createHash('md5').update(newContent).digest('hex')

			const existingContent = readFileSync(outputFile, 'utf-8')
			const hashMatch = existingContent.match(
				/Generated hash: ([a-f0-9]{32})/,
			)

			if (hashMatch && hashMatch[1] === newHash) {
				cliLogger.info(`Types are up to date: ${outputFile}`, {
					scope: 'cache-check',
				})
				return
			}
		} catch {
			// If comparison fails, continue with generation
		}
	}

	const typeDeclaration = generateConfigTypes(configDir)

	// Add hash to the generated content
	const contentHash = createHash('md5').update(typeDeclaration).digest('hex')
	const contentWithHash = typeDeclaration.replace(
		'* DO NOT EDIT MANUALLY - This file is automatically generated',
		`* DO NOT EDIT MANUALLY - This file is automatically generated\n * Generated hash: ${contentHash}`,
	)

	writeFileSync(outputFile, contentWithHash)
	cliLogger.info(`Generated config types: ${outputFile}`, {
		scope: 'type-generation',
	})
}

const main = async (): Promise<void> => {
	const { isAutoMode, paths } = parseArgs()

	// Explicit paths mode
	if (paths.length >= 2) {
		const [configDir, outputFile] = paths
		if (!configDir || !outputFile) {
			cliLogger.error('Missing required arguments', {
				scope: 'cli-validation',
			})
			process.exit(1)
		}
		generateWithPaths(configDir, outputFile)
		return
	}

	// Auto-detect mode
	const success = await autoGenerateTypes({ silent: isAutoMode })
	if (!success && !isAutoMode) {
		cliLogger.info('No config directory found', {
			scope: 'auto-detection',
		})
		process.exit(1)
	}
}

// Run and handle errors simply
main().catch(error => {
	const errorMessage = error instanceof Error ? error.message : String(error)
	cliLogger.error(`Type generation failed: ${errorMessage}`, {
		scope: 'cli-error',
	})
	process.exit(1)
})
