/**
 * Auto-generated type definitions from JSON configuration files
 * Generated from: src/config/__test-fixtures__
 * DO NOT EDIT MANUALLY - This file is automatically generated
 */

declare module '@nextnode/functions-server' {
	interface UserConfigSchema {
		app: {
			name: string
			version: string
			features: string[]
			environment: string
			debug: boolean
		}
		email: {
			from: string
			provider: string
			templates: {
				welcome: {
					subject: string
					body: string
				}
				projectRequest: {
					subject: string
					body: string
				}
			}
		}
		database: {
			host: string
			port: number
			name: string
			debug: boolean
			ssl: boolean
			connectionPoolSize: number
		}
		api: {
			baseUrl: string
			timeout: number
			retries: number
		}
		monitoring: {
			enabled: boolean
			service: string
		}
	}
}

export {}
