/**
 * Auto-generated type definitions from JSON configuration files
 * Generated from: src/__tests__/fixtures/configs
 * DO NOT EDIT MANUALLY - This file is automatically generated
 * Generated hash: 191e09a590053da75d7ad3bbc7858e00
 */

// Export direct du schema généré (Prisma-style)
export interface GeneratedConfigSchema {
	readonly api: {
		readonly baseUrl:
			| 'http://localhost:3000'
			| 'http://localhost:3001'
			| 'https://api.nextnode.com'
		readonly retries: 1 | 3 | 5
		readonly timeout: 1000 | 10000 | 3000 | 5000
	}
	readonly app: {
		readonly debug: false | true
		readonly environment: 'default' | 'development' | 'production' | 'test'
		readonly features: readonly string[]
		readonly name: 'NextNode Functions Server'
		readonly version: '1.0.0'
	}
	readonly database: {
		readonly connectionPoolSize: 10 | 20 | 5
		readonly debug: false | true
		readonly host: 'localhost' | 'prod-db.nextnode.com'
		readonly name:
			| 'nextnode_default'
			| 'nextnode_dev'
			| 'nextnode_production'
			| 'nextnode_test'
		readonly port: 5432 | 5433 | 5434
		readonly ssl: false | true
	}
	readonly email: {
		readonly from:
			| 'dev@nextnode.local'
			| 'noreply@nextnode.com'
			| 'test@nextnode.test'
		readonly provider: 'console' | 'default' | 'mock' | 'sendgrid'
		readonly templates: {
			readonly projectRequest: {
				readonly body: 'A new project has been requested.'
				readonly subject: 'New Project Request'
			}
			readonly welcome: {
				readonly body:
					| 'Test welcome message'
					| "Thank you for joining NextNode. We're excited to have you on board!"
					| 'Welcome to our development environment!'
					| 'Welcome to our platform!'
				readonly subject:
					| 'Welcome to NextNode'
					| '[DEV] Welcome to NextNode'
					| '[TEST] Welcome'
			}
		}
	}
	readonly monitoring: {
		readonly enabled: false | true
		readonly service: 'console' | 'datadog' | 'disabled'
	}
}

// Module augmentation pour remplacer ConfigSchema
declare module '@nextnode/config-manager' {
	// eslint-disable-next-line @typescript-eslint/no-empty-object-type
	interface ConfigSchema extends GeneratedConfigSchema {}
}

export {}
