/**
 * Auto-generated type definitions from JSON configuration files
 * Generated from: src/__test-fixtures__
 * DO NOT EDIT MANUALLY - This file is automatically generated
 */

declare module '@nextnode/config-manager' {
  interface UserConfigSchema {
  readonly app: {
    readonly name: string
    readonly version: string
    readonly features: readonly string[]
    readonly environment: string
    readonly debug: boolean
  }
  readonly email: {
    readonly from: string
    readonly provider: string
    readonly templates: {
      readonly welcome: {
        readonly subject: string
        readonly body: string
      }
      readonly projectRequest: {
        readonly subject: string
        readonly body: string
      }
    }
  }
  readonly database: {
    readonly host: string
    readonly port: number
    readonly name: string
    readonly debug: boolean
    readonly ssl: boolean
    readonly connectionPoolSize: number
  }
  readonly api: {
    readonly baseUrl: string
    readonly timeout: number
    readonly retries: number
  }
  readonly monitoring: {
    readonly enabled: boolean
    readonly service: string
  }
}
}

export {}
