name: Manual Publish

on:
  workflow_dispatch:
    inputs:
      dry-run:
        description: 'Run in dry-run mode (no actual publishing)'
        required: false
        default: false
        type: boolean

concurrency:
  group: manual-publish-${{ github.ref }}
  cancel-in-progress: false

jobs:
  manual-publish:
    name: Manual Publish Recovery
    uses: NextNodeSolutions/github-actions/.github/workflows/publish-release.yml@main
    permissions:
      contents: write
      id-token: write
      actions: read
      packages: write
    with:
      node-version: '20'
      pnpm-version: '10.11.0'
      publish-script: 'changeset:publish'
      build-script: 'build'
      enable-provenance: true
      dry-run: ${{ inputs.dry-run }}
      create-github-release: true
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
