name: Post Release

on:
  workflow_run:
    workflows: ["Publish Release"]
    types: [completed]
    branches: [main]

jobs:
  post-release:
    name: Post-Release Tasks
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
    
    steps:
      - name: Announce Release
        run: |
          echo "🎉 @nextnode/config-manager has been released!"
          echo "📦 NPM: https://www.npmjs.com/package/@nextnode/config-manager"