name: Publish Release

on:
  workflow_run:
    workflows: ["Version Management"]
    types: [completed]
    branches: [main]
  workflow_dispatch:

concurrency:
  group: publish-${{ github.ref }}
  cancel-in-progress: false

jobs:
  publish-release:
    name: Publish Release
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: NextNodeSolutions/github-actions/.github/workflows/publish-release.yml@main
    permissions:
      contents: write
      id-token: write
      actions: read
      packages: write
    with:
      node-version: '20'
      pnpm-version: '10.11.0'
      publish-script: 'changeset:publish'
      build-script: 'build'
      enable-provenance: true
      dry-run: false
      create-github-release: true
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}