name: Release (Centralized)

on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: false

jobs:
  release:
    name: Release Library
    uses: NextNodeSolutions/github-actions/.github/workflows/release.yml@feat/centralized-release-workflows
    with:
      # Environment configuration
      node-version: '20'
      pnpm-version: '10.11.0'
      
      # Quality checks (config-manager specific)
      run-quality-checks: true
      run-lint: true
      run-typecheck: true
      run-tests: true
      run-build: true
      test-coverage: false
      
      # Release configuration
      version-script: 'changeset:version'
      publish-script: 'changeset:publish'
      enable-provenance: true
      dry-run: false
      
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      CHANGESET_GITHUB_TOKEN: ${{ secrets.CHANGESET_GITHUB_TOKEN || secrets.GITHUB_TOKEN }}

  # Optional: Custom post-release steps specific to config-manager
  post-release:
    name: Post-Release Tasks
    needs: [release]
    if: needs.release.outputs.published == 'true'
    runs-on: ubuntu-latest
    
    steps:
      - name: Announce Release
        run: |
          echo "🎉 @nextnode/config-manager@${{ needs.release.outputs.version }} has been released!"
          echo "📦 NPM: https://www.npmjs.com/package/@nextnode/config-manager"
          echo "🔍 Published packages: ${{ needs.release.outputs.packages }}"