name: Test

on:
  pull_request:
    branches: [main, master]

jobs:
  quality:
    name: Quality Checks
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Checkout Actions
        uses: actions/checkout@v4
        with:
          repository: NextNodeSolutions/github-actions
          path: .github-actions
          sparse-checkout: actions
          
      - name: Run Quality Pipeline
        uses: ./.github-actions/actions/quality-pipeline