name: Test

on:
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    name: Quality Pipeline
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Checkout GitHub Actions
      uses: actions/checkout@v4
      with:
        repository: NextNodeSolutions/github-actions
        path: .github-actions
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Run Quality Pipeline
      uses: ./.github-actions/actions/quality-pipeline
      with:
        node-version: '20'
        pnpm-version: '10.11.0' 